image: gitpod/workspace-mysql:latest

ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

tasks:
  - name: WebServer
    init: |
      echo ------------------------------------------------------------------------
      echo Instaling Tomcat 8.5.97
      echo ------------------------------------------------------------------------
      wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.97/bin/apache-tomcat-8.5.97.tar.gz -P /workspace
      tar -xzvf /workspace/apache-tomcat-8.5.97.tar.gz -C /workspace
      rm /workspace/apache-tomcat-8.5.97.tar.gz

      echo
      echo ------------------------------------------------------------------------
      echo Instaling java-8-openjdk-amd64...
      echo ------------------------------------------------------------------------
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk
      sudo rm /usr/lib/jvm/java-1.8.0-openjdk-amd64

      echo
      echo ------------------------------------------------------------------------
      echo Creating tables...
      echo ------------------------------------------------------------------------
      mysql < DDL.sql
      sudo touch ~/tabelas_criadas
      echo
      ./startweb.sh

  - command: |
      PS1='(MySQL) $ '
      clear
      echo -----------------------------------------
      echo Aguardando a criação das tabelas...
      echo -----------------------------------------
      while true; do
        if [ -f ~/tabelas_criadas ]; then
          break
        else
          sleep 1
        fi
      done
      clear
      mysql itall_dev -e "show tables"
      echo Digite "mysql itall_dev" para entrar
    name: MySQL
      
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
