ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

image: gitpod/workspace-mysql:latest

tasks:
  # Instala o Java 1.8 e muda o ambiente para esta versão
  - init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk  
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH  

  #Cria as tabelas no banco de dados e abre o MySql
  - name: MySQL
    init: |
      while ! mysqladmin ping -h localhost --silent; do 
          sleep 1
      done
      mysql < DDL.sql

  #1) Executa o MySQL
  #2) Abre o banco de dados da aplicação
  #3) Exibe as tabelas criadas
  - command: |
      mysql itall_dev -e "show tables"

# Estas extensões são reclamadas pelo ambiente se usado o vscode.
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
