image: gitpod/workspace-mysql:latest

ports:
- name: Aplicação (FrontEnd)
  port: 8080
  onOpen: open-preview
  visibility: public

- name: MySQL
  port: 3306
  onOpen: notify
  visibility: private

tasks:
  # Instala o Java 1.8 e o TomCat 8.5
  - init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk  
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH  

  #Cria as tabels no banco de dados e abre o MySql
  - name: MySQL
    init: mysql < DDL.sql

  #Executa o MySQ, abre o banco de dados da aplicação e exibe as tabelas criadas
  - command: mysql itall_dev -e "show tables"


vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
