tasks:
  - command: echo 'sem openMode'
  - command: echo 'split-left'
    openMode: split-left
  - command: echo 'split-right'
    openMode: split-right
  - command: echo 'after'
    openMode: tab-after
  - command: echo 'before'
    openMode: tab-before
    