image: gitpod/workspace-mysql:latest

ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

tasks:
  - name: WebServer
    init: |
      echo ----------------
      echo Iniciando...
      echo ----------------
      wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.70/bin/apache-tomcat-8.5.70.tar.gz -P ~
      tar -xzvf ~/apache-tomcat-8.5.70.tar.gz -C ~
      rm ~/apache-tomcat-8.5.70.tar.gz
      export CATALINA_HOME=$HOME/apache-tomcat-8.5.70
      export PATH=$CATALINA_HOME/bin:$PATH
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
