image: gitpod/workspace-mysql:latest

ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

tasks:
  # Instala o Java 1.8 e muda o ambiente para esta versão
  - name: Server
    init: |
      clear
      echo "-----------------------------------------"
      echo "Instalando o Java 8...
      echo "-----------------------------------------"
      sudo apt-get update

# Estas extensões são reclamadas pelo ambiente se usado o vscode.
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
