ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

image: gitpod/workspace-mysql:latest

tasks:
  # Instala o Java 1.8 e muda o ambiente para esta versão
  - name: Server
    init: |
      clear
      echo "-----------------------------------------"
      echo "Instalando o Java 8...
      echo "-----------------------------------------"
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk  
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH  
  
  # Exibe as tabelas criadas no banco
  - openMode: split-left
    name: MySQL
    command: |
      PS1='MySQL:$ '
      clear
      echo "-----------------------------------------"
      echo "Aguardando a criação das tabelas..."
      echo "-----------------------------------------"
      while true; do
        if [ -f /usr/lib/jvm/java-8-openjdk-amd64/tabelas_criadas ]; then
          break
        else
          sleep 1
        fi
      done
      clear
      mysql itall_dev

# Estas extensões são reclamadas pelo ambiente se usado o vscode.
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
