image: gitpod/workspace-mysql:latest

ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
