image: gitpod/workspace-mysql:latest

ports:
- port: 8080
  name: WebSite
  onOpen: open-browser
  visibility: public

- port: 3306
  name: MySQL
  onOpen: ignore
  visibility: private

tasks:
  - name: WebServer
    init: |
      echo ------------------------------------------------------------------------
      echo Instaling Tomcat 8.5.97
      echo ------------------------------------------------------------------------
      wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.97/bin/apache-tomcat-8.5.97.tar.gz -P ~
      tar -xzvf ~/apache-tomcat-8.5.97.tar.gz -C ~
      rm ~/apache-tomcat-8.5.97.tar.gz
      export CATALINA_HOME=$HOME/apache-tomcat-8.5.97
      export CATALINA_BASE=$CATALINA_HOME
      export PATH=$CATALINA_HOME/bin:$PATH
      export CATALINA_TMPDIR=$CATALINA_HOME/temp
      export CLASSPATH=$CATALINA_HOME/bin/bootstrap.jar;$CATALINA_HOME/bin/tomcat-juli.jar
      export MAVEN_OPTS=-Dfile.encoding=UTF-8
      export CATALINA_OPTS=-Dfile.encoding=UTF-8

      echo
      echo ------------------------------------------------------------------------
      echo Instaling java-8-openjdk-amd64...
      echo ------------------------------------------------------------------------
      sudo apt-get update
      sudo apt-get install -y openjdk-8-jdk
      sudo rm /usr/lib/jvm/java-1.8.0-openjdk-amd64
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export JRE_HOME=$JAVA_HOME
      export PATH=$JAVA_HOME/bin:$PATH
      echo
      echo ------------------------------------------------------------------------
      echo Criando as tabelas no banco de dados...
      echo ------------------------------------------------------------------------
      mysql < DDL.sql

  - command: |
      PS1='(MySQL):$ '
      clear
      echo Digite "mysql ital_dev" para entrar
    openIn: right
    openMode: tab-after

      
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
